# Generated by Django 5.1.1 on 2025-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5QsDIFym3ROJQAeJSRQhQfRlux0aSsYc', editable=False, max_length=32, unique=True),
        ),
    ]
