# Generated by Django 5.1.1 on 2025-09-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vAOcOEbId19hwT23mu5aII603lWLVEdR', editable=False, max_length=32, unique=True),
        ),
    ]
