# Generated by Django 5.1.1 on 2025-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='bkP5peLH5mqrfBdWSSGSVIKloPfZ8b2f', editable=False, max_length=32, unique=True),
        ),
    ]
