# Generated by Django 5.1.1 on 2025-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xKMBND2igYpnylIaU0WlijGTZNqewB7L', editable=False, max_length=32, unique=True),
        ),
    ]
